### ISSUE TITLE
Requesting attachments for documents

### ISSUE THREAD

**Issue by NatashaShahith** [shahithabdul/Whatsapp_Config#4]
Dear Shahith,

It would be great if the app has feature to attach documents as well. Kindly add this feature.

**Comment by shahithabdul** [comment]
Dear Natasha, thanks for suggesting this feature . we will add and let you know

**Comment by shahithabdul** [comment]
Thanks for your suggestion

**Comment by shahithabdul** [comment]
Thanks for your suggestion. We will work together to get a Better product
